name: Test Kitchen

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-{{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  kitchen:
    name: Test Kitchen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - nominatim
        os:
          - ubuntu-2204
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run kitchen test ${{ matrix.suite }}-${{ matrix.os }}
      run: bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }}
